# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stockd' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stockd
  pod 'Charts'
  pod 'FacebookLogin'
  pod 'FacebookCore'
  pod 'FBSDKCoreKit', '~> 4.38.1'
  pod 'FBSDKLoginKit', '~> 4.38.1'
  pod 'lottie-ios'
  pod 'GoogleSignIn'

end
